#!/usr/bin/env bash

############## LSTM Cell
#### NASS AUSTRALIAN EMS CALLS DATASET
###  DeepCPNet Framework
## window size 15 + 1 (STL decomposition as exogenous variable) = 16
## forecasting horizon 12

# without stl decomposition
#stacking_moving_window_smac_cocob
# python ./generic_model_handler.py --dataset_name ems12i15_without_stl --contain_zero_values 0 --initial_hyperparameter_values_file configs/initial_hyperparameter_values/ems_adagrad --binary_train_file_train_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/ems_12i15.tfrecords --binary_valid_file_train_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/ems_12i15v.tfrecords --binary_train_file_test_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/ems_12i15v.tfrecords --binary_test_file_test_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/ems_test_12i15.tfrecords --txt_test_file datasets/text_data/EMS/moving_window/without_stl_decomposition/ems_test_12i15.txt --actual_results_file datasets/text_data/EMS/ems_results.txt --input_size 16 --forecast_horizon 12 --no_of_series 79 --optimizer cocob --seasonality_period 12 --original_data_file datasets/text_data/EMS/ems_dataset.txt --address_near_zero_instability 0 --without_stl_decomposition 1 &

#stacking_moving_window_smac_adagrad
#python ./generic_model_handler.py --dataset_name ems12i15_without_stl --contain_zero_values 0 --initial_hyperparameter_values_file configs/initial_hyperparameter_values/ems_adagrad --binary_train_file_train_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/ems_12i15.tfrecords --binary_valid_file_train_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/ems_12i15v.tfrecords --binary_train_file_test_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/ems_12i15v.tfrecords --binary_test_file_test_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/ems_test_12i15.tfrecords --txt_test_file datasets/text_data/EMS/moving_window/without_stl_decomposition/ems_test_12i15.txt --actual_results_file datasets/text_data/EMS/ems_results.txt --input_size 16 --forecast_horizon 12 --no_of_series 79 --optimizer adagrad --seasonality_period 12 --original_data_file datasets/text_data/EMS/ems_dataset.txt --address_near_zero_instability 0 --without_stl_decomposition 1 &

#stacking_moving_window_smac_adam
#python ./generic_model_handler.py --dataset_name ems12i15_without_stl --contain_zero_values 0 --initial_hyperparameter_values_file configs/initial_hyperparameter_values/ems_adam --binary_train_file_train_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/ems_12i15.tfrecords --binary_valid_file_train_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/ems_12i15v.tfrecords --binary_train_file_test_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/ems_12i15v.tfrecords --binary_test_file_test_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/ems_test_12i15.tfrecords --txt_test_file datasets/text_data/EMS/moving_window/without_stl_decomposition/ems_test_12i15.txt --actual_results_file datasets/text_data/EMS/ems_results.txt --input_size 16 --forecast_horizon 12 --no_of_series 79 --optimizer adam --seasonality_period 12 --original_data_file datasets/text_data/EMS/ems_dataset.txt --address_near_zero_instability 0 --without_stl_decomposition 1 &

###############
###  DeepCPNet-ALI variant (using alcohol licenses issuing as exogenous variable)
## window size 30 + 1 (STL decomposition as exogenous variable) = 31
## forecasting horizon 12

#stacking_moving_window_smac_cocob
#python ./generic_model_handler.py --dataset_name emsEX_without_stl --contain_zero_values 0 --initial_hyperparameter_values_file configs/initial_hyperparameter_values/ems_adagrad --binary_train_file_train_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/emsEX_12i15.tfrecords --binary_valid_file_train_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/emsEX_12i15v.tfrecords --binary_train_file_test_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/emsEX_12i15v.tfrecords --binary_test_file_test_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/emsEX_test_12i15.tfrecords --txt_test_file datasets/text_data/EMS/moving_window/without_stl_decomposition/emsEX_test_12i15.txt --actual_results_file datasets/text_data/EMS/ems_results.txt --input_size 31 --forecast_horizon 12 --no_of_series 79 --optimizer cocob --seasonality_period 12 --original_data_file datasets/text_data/EMS/ems_dataset.txt --address_near_zero_instability 0 --without_stl_decomposition 1 &

#stacking_moving_window_smac_adagrad
#python ./generic_model_handler.py --dataset_name emsEX_without_stl --contain_zero_values 0 --initial_hyperparameter_values_file configs/initial_hyperparameter_values/ems_adagrad --binary_train_file_train_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/emsEX_12i15.tfrecords --binary_valid_file_train_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/emsEX_12i15v.tfrecords --binary_train_file_test_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/emsEX_12i15v.tfrecords --binary_test_file_test_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/emsEX_test_12i15.tfrecords --txt_test_file datasets/text_data/EMS/moving_window/without_stl_decomposition/emsEX_test_12i15.txt --actual_results_file datasets/text_data/EMS/ems_results.txt --input_size 31 --forecast_horizon 12 --no_of_series 79 --optimizer adagrad --seasonality_period 12 --original_data_file datasets/text_data/EMS/ems_dataset.txt --address_near_zero_instability 0 --without_stl_decomposition 1 &

#stacking_moving_window_smac_adam
#python ./generic_model_handler.py --dataset_name emsEX_without_stl --contain_zero_values 0 --initial_hyperparameter_values_file configs/initial_hyperparameter_values/ems_adam --binary_train_file_train_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/emsEX_12i15.tfrecords --binary_valid_file_train_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/emsEX_12i15v.tfrecords --binary_train_file_test_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/emsEX_12i15v.tfrecords --binary_test_file_test_mode datasets/binary_data/EMS/moving_window/without_stl_decomposition/emsEX_test_12i15.tfrecords --txt_test_file datasets/text_data/EMS/moving_window/without_stl_decomposition/emsEX_test_12i15.txt --actual_results_file datasets/text_data/EMS/ems_results.txt --input_size 31 --forecast_horizon 12 --no_of_series 79 --optimizer adam --seasonality_period 12 --original_data_file datasets/text_data/EMS/ems_dataset.txt --address_near_zero_instability 0 --without_stl_decomposition 1 &

###############################################################################################################################################################
### 911 ·
python ./generic_model_handler.py --dataset_type calls911 --dataset_name callsMT2 --contain_zero_values 0 --forecast_horizon 7 --no_of_series 62 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &

### sim
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_10_60_l_he --contain_zero_values 0 --forecast_horizon 12 --no_of_series 10 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_10_60_l_ho --contain_zero_values 0 --forecast_horizon 12 --no_of_series 10 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_10_60_nl_he --contain_zero_values 0 --forecast_horizon 12 --no_of_series 10 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_10_60_nl_ho --contain_zero_values 0 --forecast_horizon 12 --no_of_series 10 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_10_222_l_he --contain_zero_values 0 --forecast_horizon 12 --no_of_series 10 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_10_222_l_ho --contain_zero_values 0 --forecast_horizon 12 --no_of_series 10 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_10_222_nl_he --contain_zero_values 0 --forecast_horizon 12 --no_of_series 10 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_10_222_nl_ho --contain_zero_values 0 --forecast_horizon 12 --no_of_series 10 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_101_60_l_he --contain_zero_values 0 --forecast_horizon 12 --no_of_series 101 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_101_60_l_ho --contain_zero_values 0 --forecast_horizon 12 --no_of_series 101 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_101_60_nl_he --contain_zero_values 0 --forecast_horizon 12 --no_of_series 101 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_101_60_nl_ho --contain_zero_values 0 --forecast_horizon 12 --no_of_series 101 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_101_222_l_he --contain_zero_values 0 --forecast_horizon 12 --no_of_series 101 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_101_222_l_ho --contain_zero_values 0 --forecast_horizon 12 --no_of_series 101 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_101_222_nl_he --contain_zero_values 0 --forecast_horizon 12 --no_of_series 101 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_101_222_nl_ho --contain_zero_values 0 --forecast_horizon 12 --no_of_series 101 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_500_60_l_he --contain_zero_values 0 --forecast_horizon 12 --no_of_series 500 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_500_60_l_ho --contain_zero_values 0 --forecast_horizon 12 --no_of_series 500 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_500_60_nl_he --contain_zero_values 0 --forecast_horizon 12 --no_of_series 500 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_500_60_nl_ho --contain_zero_values 0 --forecast_horizon 12 --no_of_series 500 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_500_222_l_he --contain_zero_values 0 --forecast_horizon 12 --no_of_series 500 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_500_222_nl_he --contain_zero_values 0 --forecast_horizon 12 --no_of_series 500 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_500_222_nl_ho --contain_zero_values 0 --forecast_horizon 12 --no_of_series 500 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &
python ./generic_model_handler.py --dataset_type sim --dataset_name sim_500_222_l_ho --contain_zero_values 0 --forecast_horizon 12 --no_of_series 500 --optimizer cocob --seasonality_period 12 --address_near_zero_instability 0 --without_stl_decomposition 1 &



# python ./benchmark_model_handler.py --model DeepProbCP --dataset_name calls911_benchmarks --feature_type 'MS' --initial_hyperparameter_values_file configs/initial_hyperparameter_values/ems_DeepProbCP_cocob --no_of_series 62 --input_size 15 --forecast_horizon 7 --optimizer cocob --seasonality_period 12 --original_data_file datasets/text_data/calls911/callsMT2_dataset.txt --address_near_zero_instability 0 --without_stl_decomposition 1 &
# python ./benchmark_model_handler.py --model CausalImpact --dataset_name calls911_benchmarks --feature_type 'MS' --initial_hyperparameter_values_file configs/initial_hyperparameter_values/ems_DeepProbCP_cocob --no_of_series 62 --input_size 15 --forecast_horizon 7 --optimizer cocob --seasonality_period 12 --original_data_file datasets/text_data/calls911/callsMT2_dataset.txt --address_near_zero_instability 0 --without_stl_decomposition 1 &

#stacking_moving_window_smac_adagrad
#python ./generic_model_handler.py --dataset_name callsMT215_without_stl --contain_zero_values 0 --initial_hyperparameter_values_file configs/initial_hyperparameter_values/ems_adagrad --binary_train_file_train_mode datasets/binary_data/calls911/moving_window/without_stl_decomposition/callsMT2_7_15.tfrecords --binary_valid_file_train_mode datasets/binary_data/calls911/moving_window/without_stl_decomposition/callsMT2_7_15v.tfrecords --binary_train_file_test_mode datasets/binary_data/calls911/moving_window/without_stl_decomposition/callsMT2_7_15v.tfrecords --binary_test_file_test_mode datasets/binary_data/calls911/moving_window/without_stl_decomposition/callsMT2_test_7_15.tfrecords --txt_test_file datasets/text_data/calls911/moving_window/without_stl_decomposition/callsMT2_test_7_15.txt --actual_results_file datasets/text_data/calls911/callsMT2_results.txt --input_size 16 --forecast_horizon 7 --no_of_series 62 --optimizer adagrad --seasonality_period 12 --original_data_file datasets/text_data/calls911/callsMT2_dataset.txt --address_near_zero_instability 0 --without_stl_decomposition 1 &

